
1. Импорт библиотеки NumPy с общепринятым сокращением.

In [66]:
import numpy as np
import pandas as pd

In [67]:
a = np.array([1, 2, 3])

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [68]:
np.zeros(3)

array([0., 0., 0.])

In [69]:
np.ones(3)

array([1., 1., 1.])

In [70]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [71]:
a.shape

(3,)

In [72]:
a.dtype

dtype('int64')

4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [73]:
b = np.arange(1, 10+1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
b[0]

np.int64(1)

In [75]:
b[3:7]

array([4, 5, 6, 7])

In [76]:
b[:5:2]

array([1, 3, 5])

In [77]:
b[::2]

array([1, 3, 5, 7, 9])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [78]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [79]:
c = a*b
c

array([ 4, 10, 18])

In [80]:
c.mean()

np.float64(10.666666666666666)

In [81]:
c.min()

np.int64(4)

In [82]:
c.max()

np.int64(18)