
1. Импорт библиотеки NumPy с общепринятым сокращением.

In [84]:
import numpy as np
import pandas as pd

In [85]:
a = np.array([1, 2, 3])

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [86]:
np.zeros(3)

array([0., 0., 0.])

In [87]:
np.ones(3)

array([1., 1., 1.])

In [88]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [89]:
a.shape

(3,)

In [90]:
a.dtype

dtype('int64')

4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [91]:
b = np.arange(1, 10+1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
b[0]

np.int64(1)

In [93]:
b[3:7]

array([4, 5, 6, 7])

In [94]:
b[:5:2]

array([1, 3, 5])

In [95]:
b[::2]

array([1, 3, 5, 7, 9])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [96]:
a = np.array([[1, 2, 3], [10, 20, 30]])
b = np.array([[4, 5, 6], [7, 8, 9]])
a+b

array([[ 5,  7,  9],
       [17, 28, 39]])

In [97]:
c = a*b
c

array([[  4,  10,  18],
       [ 70, 160, 270]])

In [98]:
c.mean()

np.float64(88.66666666666667)

In [99]:
c.min()

np.int64(4)

In [100]:
c.max()

np.int64(270)